import requests

payload = [{
            'name': 'receiver.hpp',
            'file_type_id': 1,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/atomics'
           }, {
            'name': 'sender.hpp',
            'file_type_id': 1,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/atomics'
           }, {
            'name': 'subnet.hpp',
            'file_type_id': 1,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/atomics'
           }, {
            'name': 'message.cpp',
            'file_type_id': 5,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/data_structures'
           }, {
            'name': 'message.hpp',
            'file_type_id': 4,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/data_structures'
           }, {
            'name': 'input_abp_0.txt',
            'file_type_id': 8,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/input_data'
           }, {
            'name': 'input_abp_1.txt',
            'file_type_id': 8,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/input_data'
           }, {
            'name': 'ABP_output_messages.txt',
            'file_type_id': 10,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/simulation_results'
           }, {
            'name': 'ABP_output_state.txt',
            'file_type_id': 9,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/simulation_results'
           }, {
            'name': 'messages.log',
            'file_type_id': 12,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/simulation_results'
           }, {
            'name': 'structure.json',
            'file_type_id': 11,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/simulation_results'
           }, {
            'name': 'main.cpp',
            'file_type_id': 3,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/top_model'
           }, {
            'name': 'alternatebitprot.doc',
            'file_type_id': 17,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol'
           }, {
            'name': 'makefile',
            'file_type_id': 6,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol'
           }, {
            'name': 'README.txt',
            'file_type_id': 17,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol'
           }, {
            'name': 'hospital.hpp',
            'file_type_id': 1,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/atomics'
           }, {
            'name': 'emergency_area.hpp',
            'file_type_id': 1,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/atomics'
           }, {
            'name': 'emergency_areas.geojson',
            'file_type_id': 7,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/data/Ottawa-Gatineau'
           }, {
            'name': 'hospitals.geojson',
            'file_type_id': 7,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/data/Ottawa-Gatineau'
           }, {
            'name': 'network.geojson',
            'file_type_id': 7,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/data/Ottawa-Gatineau'
           }, {
            'name': 'simulation_area.geojson',
            'file_type_id': 7,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/data/Ottawa-Gatineau'
           }, {
            'name': 'emergency.hpp',
            'file_type_id': 4,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/data_structures'
           }, {
            'name': 'output_messages.txt',
            'file_type_id': 10,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/simulation_results'
           }, {
            'name': 'state_messages.txt',
            'file_type_id': 9,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/simulation_results'
           }, {
            'name': 'messages.log',
            'file_type_id': 12,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/simulation_results'
           }, {
            'name': 'structure.json',
            'file_type_id': 11,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/simulation_results'
           }, {
            'name': 'main.cpp',
            'file_type_id': 3,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/top_model'
           }, {
            'name': 'makefile',
            'file_type_id': 6,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital'
           }, {
            'name': 'abp_experiment_1.json',
            'file_type_id': 16,
            'last_modification': '2010-01-01',
            'last_author_id': 1,
            'path': 'alternating-bit-protocol/experiments'
           }, {
            'name': 'gis_emergencies_experiment_1.json',
            'file_type_id': 16,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/experiments'
           }, {
            'name': 'diagram.drawio',
            'file_type_id': 17,
            'last_modification': '2021-03-04',
            'last_author_id': 2,
            'path': 'alternating-bit-protocol/visualization'
           }, {
            'name': 'diagram.svg',
            'file_type_id': 15,
            'last_modification': '2021-03-04',
            'last_author_id': 2,
            'path': 'alternating-bit-protocol/visualization'
           }, {
            'name': 'visualization.json',
            'file_type_id': 13,
            'last_modification': '2021-07-01',
            'last_author_id': 2,
            'path': 'cadmium-geo-hospital/visualization'
           }]

r = requests.post('http://localhost:8080/api/files', json=payload)

print(r.status_code)
